apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-system
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
